version: '3'
services:
  web:
    build: .
    ports:
      - "80:3000"
    command: bundle exec puma
    volumes:
      - ./src:/src/app_name
      - bundle-data:/bundle
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  bundle-data:
  db-data: